language: node_js
node_js:
- node
notifications:
  email: false
deploy:
  provider: heroku
  api_key:
    secure: cf82551e-b6f8-4dec-86aa-d28174146b2b
    app: ci-attempt-3
    on:
      branch: main
